version: "3.9"
services:
  api:
    build:
      context: ../
      dockerfile: build/package/chameleon-api-server/Dockerfile
    ports:
      - 8000:8000
  mtd:
    build:
      context: ../
      dockerfile: build/package/chameleon-mtd/Dockerfile
    ports:
      - 25:25
