version: "3.9"
services:
  database:
    restart: always
    image: 'mongo:latest'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: chameleon
      MONGO_INITDB_ROOT_PASSWORD: chameleon

  api:
    build:
      context: ../
      dockerfile: build/package/chameleon-api/Dockerfile
    ports:
      - 8000:8000
    environment:
      CHAMELEON_API_SERVER_PORT: 8000
      CHAMELEON_API_SERVER_DATABASE_HOST: database
      CHAMELEON_API_SERVER_DATABASE_PORT: 27017
      CHAMELEON_API_SERVER_DATABASE_USER: chameleon
      CHAMELEON_API_SERVER_DATABASE_PASSWORD: chameleon
      CHAMELEON_API_SERVER_DATABASE_DATABASE: chameleon
      CHAMELEON_LOG_LEVEL: trace
    depends_on:
      - database

  mtd:
    build:
      context: ../
      dockerfile: build/package/chameleon-mtd/Dockerfile
    ports:
      - 25:25
    environment:
      CHAMELEON_MTD_API_URL: http://api/
      CHAMELEON_MTD_SMTP_XCLIENT_ON: 'true'
    depends_on:
      - api