version: "3.9"
services:
  database:
    build:
      context: ../
      dockerfile: build/package/database/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: chameleon
      POSTGRES_PASSWORD: chameleon
      POSTGRES_DB: chameleon
      API_USER: api
      API_PASSWORD: api
      API_DB: api
  api:
    build:
      context: ../
      dockerfile: build/package/chameleon-api/Dockerfile
    ports:
      - 8000:8000
  mtd:
    build:
      context: ../
      dockerfile: build/package/chameleon-mtd/Dockerfile
    ports:
      - 25:25
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: chameleon
      POSTGRES_PASSWORD: chameleon
      POSTGRES_DB: chameleon