version: "3.9"
services:
  database:
    build:
      context: ../
      dockerfile: build/package/database/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: chameleon
      POSTGRES_PASSWORD: chameleon
      POSTGRES_DB: chameleon
      API_USER: api
      API_PASSWORD: api
      API_DB: api

  api:
    build:
      context: ../
      dockerfile: build/package/chameleon-api/Dockerfile
    ports:
      - 8000:8000
    environment:
      CHAMELEON_API_SERVER_PORT: 8000
      CHAMELEON_API_SERVER_DATABASE_HOST: database
      CHAMELEON_API_SERVER_DATABASE_PORT: 5432
      CHAMELEON_API_SERVER_DATABASE_USER: api
      CHAMELEON_API_SERVER_DATABASE_PASSWORD: api
      CHAMELEON_API_SERVER_DATABASE_DATABASE: api
    depends_on:
      - database

  mtd:
    build:
      context: ../
      dockerfile: build/package/chameleon-mtd/Dockerfile
    ports:
      - 25:25
    environment:
      CHAMELEON_MTD_API_URL: http://api/
      CHAMELEON_MTD_SMTP_XCLIENT_ON: 'true'
    depends_on:
      - api