version: "3.9"
services:
  api:
    build:
      context: ../
      dockerfile: build/package/chameleon-api-server/Dockerfile
    ports:
      - 8000:8000
  smtp:
    build:
      context: ../
      dockerfile: build/package/chameleon-smtp-server/Dockerfile
    ports:
      - 25:25
