server:
  port: 80
  certificate-file:
  key-file:
  database:
    host: localhost
    port: 5432
    user: chameleon
    password: chameleon
    database: chameleon
log:
  directory: ./logs
  level: Debug